[package]
name = "rust-nmshd"
version = "0.1.0"
edition = "2021"

[dependencies]
rand_core = { version = "*", features = ["std"] }
ed25519-dalek = { version = "*", features = ["rand_core"] }
base64 = "*"
